### PR TITLE
🐛 Fix disposed provider throwing error when fetching assets

### LINKED ISSUE #492: [BUG] Exception when closing the picker before it has had time to load the assets
**Describe the bug**
Reproducible on the current example application.
When the picker is closed before it has had time to load the assets, an exception is thrown.

```
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: A DefaultAssetPickerProvider was used after being disposed.
Once you have called dispose() on a DefaultAssetPickerProvider, it can no longer be used.
#0      ChangeNotifier.debugAssertNotDisposed.<anonymous closure>
change_notifier.dart:179
#1      ChangeNotifier.debugAssertNotDisposed
change_notifier.dart:186
#2      ChangeNotifier.notifyListeners
change_notifier.dart:382
#3      DefaultAssetPickerProvider.getAssetsFromPath.run
asset_picker_provider.dart:374
<asynchronous suspension>
```

**How to reproduce**

1. Run the example app
2. Click on 'Common Picker'
3. Close it immediately after opening
4. Error occurred.

**Expected behavior**
There should be no exceptions.

**Screenshots (If contains)**

https://github.com/fluttercandies/flutter_wechat_assets_picker/assets/22376981/8d4a99e6-13dd-4148-9162-b3c98831efdd

**Version information**

- Device: iPhone 11 pro
- OS: iOS 16.2
- Package Version: 8.7.1
- Flutter Version: 3.13.3

### PR DESCRIPTION
**Pull request by LeGoffMael**
Fix #492

### CODE REVIEW

File: lib/src/provider/asset_picker_provider.dart [hunk 1]
```diff
@@ -56,13 +56,25 @@ abstract class AssetPickerProvider<Asset, Path> extends ChangeNotifier {
...
     _currentAssets.clear();
     super.dispose();
   }
 
+  @override
+  void notifyListeners() {
+    if (_mounted) {
+      super.notifyListeners();
+    }
+  }
```
Comment (LeGoffMael) [inline lib/src/provider/asset_picker_provider.dart:72]: This part is actually optional since it is not needed to fix #492 issue.
However `notifyListeners()` will throw an exception if the provider was disposed, so i thought it was still good to put a flag on it.

File: lib/src/provider/asset_picker_provider.dart [hunk 2]
```diff
@@ -490,6 +502,8 @@ class DefaultAssetPickerProvider
     final PathWrapper<AssetPathEntity> wrapper = _currentPath!;
     final int assetCount =
         wrapper.assetCount ?? await wrapper.path.assetCountAsync;
+    // If the picker was disposed (#492), stop fetching the assets
+    if (!mounted) return;
```
Comment (AlexV525) [inline lib/src/provider/asset_picker_provider.dart:506]: I was wondering why this line doesn't hit the linter rule. It should be
```suggestion
    if (!mounted) {
      return;
    }
```

File: lib/src/provider/asset_picker_provider.dart [hunk 3]
```diff
@@ -56,13 +56,25 @@ abstract class AssetPickerProvider<Asset, Path> extends ChangeNotifier {
   /// 销毁时重置所有内容
   @override
   void dispose() {
+    _mounted = false;
```
Comment (AlexV525) [inline lib/src/provider/asset_picker_provider.dart:59]: Maybe put this line before `super.dispose` to match its semantics.

**Review by AlexV525 — APPROVED** [review]
nits

File: lib/src/provider/asset_picker_provider.dart (hunk 2 above)
Comment (LeGoffMael) [reply lib/src/provider/asset_picker_provider.dart:506]: If you're speaking about the `curly_braces_in_flow_control_structures` linter rule. There is an exception when the if statement and the body fit in one line (c.f. [curly_braces_in_flow_control_structures](https://dart.dev/tools/linter-rules/curly_braces_in_flow_control_structures)).

That's the reason, but if you prefer, i will add the curly braces.

File: lib/src/provider/asset_picker_provider.dart (hunk 3 above)
Comment (LeGoffMael) [reply lib/src/provider/asset_picker_provider.dart:59]: sure

**Review by AlexV525 — APPROVED** [review]
LGTM

**Comment by LeGoffMael** [comment]
I there anything needed to merge this PR ? (my commits were not verified but it should now be fine in my next commits)

**Comment by AlexV525** [comment]
> I there anything needed to merge this PR ?

Nope. Just forgot to press the button. :)
